#ifndef GAME_SETTINGS_H
#define GAME_SETTINGS_H

#define GAME_WIDTH 640
#define GAME_HEIGHT 480	
#define GAME_TITLE "Pong"

#define GAME_FONT_SIZE 64
#define GAME_PLAYER_ONE_SCORE_X GAME_WIDTH / 4 - (GAME_FONT_SIZE / 2)
#define GAME_SCORE_Y 15
#define GAME_PLAYER_TWO_SCORE_X GAME_WIDTH - (GAME_WIDTH / 4) - (GAME_FONT_SIZE / 2)

#endif
